### ISSUE TITLE
Error in node v5.11.0

### ISSUE THREAD

**Issue by gaurav113** [vanng822/gps-util#6]
module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/gauravd/DayUsers/gauravd/Official/Projects/OLG/leadgeneration/node_modules/gps-util/node_modules/mmmagic/build/Release/magic.node: undefined symbol: _ZN2v811HandleScopeC1Ev
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gauravd/DayUsers/gauravd/Official/Projects/OLG/leadgeneration/node_modules/gps-util/node_modules/mmmagic/index.js:3:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gauravd/DayUsers/gauravd/Official/Projects/OLG/leadgeneration/node_modules/gps-util/lib/gpx-parser.js:5:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by vanng822** [comment]
Hi @gaurav113 

This is a repeating issue from mmmagic which was the main reason why I removed this dep in v1.0. The package may be less secure but shouldn't be a problem.

Try v1.0 instead and be aware of the changes
Thank you
